### ISSUE TITLE
PBR Support

### ISSUE THREAD

**Issue by HastyBasher** [uItimatech/BountifulBlocks#8]
Nice mod. It may not be your area of expertise but if it is, would you add PBR support? the blocks are cool but dont fit with shaders.

**Comment by uItimatech** [comment]
PBR support is usually done through ressource packs. It will not be added to the base mode.

**Comment by LOLZSICKA** [comment]
i _may_ attempt to commission a guy for a 16x pbr resourcepack for this mod. don't get your hopes up because 555 blocks worth of pbr may get expensive because that would be about 1.6k additional textures

if i move anywhere with this, i'll come back here with an update (do have it planned to have the guy upload to modrinth though)
